name = "gleam-package-mcp"
main = "src/index.mjs"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "gleam build"

[[d1_databases]]
binding = "DB"
database_name = "mcp-packages-cache"
database_id = "d52e04bf-5716-419a-a159-f64919993d45"

# Uncomment to add a custom domain
# [routes]
# pattern = "your-domain.com/*"
# zone_name =[observability]
[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
